[Programmers]_소수찾기
GeonwooShin/algorithm pull request #10
Opened 2023-10-28 11:40 UTC by GeonwooShin

문제출처: https://school.programmers.co.kr/learn/courses/30/lessons/42839

2023-10-29 04:23 UTC, f-lab-jake requested changes

2023-10-29 04:23 UTC, f-lab-jake commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
`ch[i]` 확인을 앞으로 두고 고쳐봅시다.

2023-10-30 04:18 UTC, GeonwooShin commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
방문확인 로직을 우선적으로 확인하도록 로직 수정했습니다!

2023-10-30 06:00 UTC, f-lab-jake commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
앗 제가 코드를 좀 잘못읽었떤것 같습니다. 그런데 이전 히스토리가 없어서 어느부분이었는지를 모르겠네요.

일단 지금 코드에 대해서 리뷰하자면, `str`이 소수인지 검사를 매 for문 마다 해야하나요?

2023-10-30 09:41 UTC, GeonwooShin commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
수의 모든 조합을 따져보아야하고 그 조합으로 나온 숫자가 소수인지 판별해야하기 때문에 매 for문 마다 소수인지 검사해야한다고 생각했습니다!

2023-10-30 11:03 UTC, f-lab-jake commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
소수인지 확인하는 if 문에서 `i`가 쓰이질 않잖아요?

2023-10-30 11:21 UTC, GeonwooShin commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
아 그 부분을 생각하지 못했습니다!

```
function solution(numbers) {
  const n = numbers.length;
  const ch = Array.from({ length: n }, () => 0);
  const set = new Set();
  function dfs(str) {
    for (let i = 0; i < n; i++) {
      if (ch[i] === 0) {
        ch[i] = 1;
        dfs(str + numbers[i]);
        ch[i] = 0;
      }
    }
    if (str !== "") {
      if (isPrime(parseInt(str))) {
        set.add(parseInt(str));
      }
    }
  }
  dfs("");
  return set.size;
}
```

위와 같이 코드를 수정하면 `for`문 밖에서만 확인하면 되겠네요!

2023-10-30 13:15 UTC, f-lab-jake commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
위 코드를 실행하면 길이가 긴소수부터 `set`에 추가되는걸 알고있나요?

2023-10-30 14:56 UTC, GeonwooShin commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
네 for문에서 dfs를 반복적으로 실행하기 때문에 예를 들어 `numbers = "17"`이라면 17, 1, 71, 7 순으로 소수 판별을 해서 set에 추가됩니다!

2023-10-31 06:18 UTC, f-lab-jake commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
길이가 짧은 소수부터 추가되게 하려면 어떻게해야할까요?

2023-10-31 08:16 UTC, GeonwooShin commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
```
function solution(numbers) {
  const n = numbers.length;
  const ch = Array.from({ length: 10 }, () => 0);
  const set = new Set();
  const queue = numbers.split("");
  while (queue.length) {
    const str = queue.shift(); // "1"
    str.split("").forEach((v) => (ch[v] = 1));
    if (isPrime(parseInt(str))) {
      set.add(parseInt(str));
    }
    for (let num of numbers) {
      if (ch[num] === 0) {
        queue.push(str + num);
      }
    }
  }
  return set.size;
}
```

짧은 소수부터 추가되게 하기 위해서 bfs를 사용해봤는데 bfs로는 방문체크로직을 어떻게 작성해야할지 감이 안잡히네요 ㅠㅠ
dfs로도 짧은 소수부터 추가되게 할 수 있나요? 어떻게 접근해야할지 모르겠습니다!

2023-10-31 15:04 UTC, f-lab-jake commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
```js
if (str !== "") {
  if (isPrime(parseInt(str))) {
    set.add(parseInt(str));
  }
}
for (let i = 0; i < n; i++) {
  if (ch[i] === 0) {
    ch[i] = 1;
    dfs(str + numbers[i]);
    ch[i] = 0;
  }
}
```

요렇게 순서를 바꾸는것 만으로 됩니다. 사실 정확하게 길이가 짧은순->긴순으로 되진 않는데요(순서 바꾸기 전에도 정확히 긴순->짧은순 으로 되진 않습니다).

순서 바꾼것에따라 왜 동작이 바뀌는지 한번 고민해봅시다

2023-11-01 13:04 UTC, GeonwooShin commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
기존에는 `for`문이 반복적으로 실행되면서 수가 길어지고 더이상 방문할 숫자가 없어지면 그제서야 소수인지 판별했었는데
변경된 코드에서는 숫자가 하나씩 늘어날 때마다 소수 판별을 먼저진행하기 때문에 짧은 숫자가 먼저 set에 추가되겠네요!

```
function isPrime(num) {
  if (num < 2) return false;
  for (let i = 2; i <= Math.sqrt(num); i++) {
    if (num % i === 0) return false;
  }
  return true;
}

function solution(numbers) {
  const n = numbers.length;
  const ch = Array.from({ length: n }, () => 0);
  const set = new Set();
  function dfs(str) {
    if (str !== "") {
      if (isPrime(parseInt(str))) {
        set.add(parseInt(str));
      }
    }
    for (let i = 0; i < n; i++) {
      if (ch[i] === 0) {
        ch[i] = 1;
        dfs(str + numbers[i]);
        ch[i] = 0;
      }
    }
  }
  dfs("");
  return set.size;
}

console.log(solution("17"));
```
그럼 결과적으로 위 코드가 될것같습니다!

2023-11-02 01:57 UTC, f-lab-jake approved these changes

2023-11-02 01:57 UTC, f-lab-jake commented on Programmers/level2/소수찾기.js
> +        ch[i] = 1;
맞습니다. 이문제에선 순서가 상관없는데, 문제에 따라 따지는 경우도 있습니다. 이때 재귀호출의 위치에 따른 동작의 차이를 알아야 고칠수있습니다.

2023-11-02 06:44 UTC, merged