[BOJ]_단지번호붙이기
GeonwooShin/algorithm pull request #11
Opened 2023-11-02 08:28 UTC by GeonwooShin

문제 출처: https://www.acmicpc.net/problem/2667

DFS를 사용해서 풀었습니다.

2023-11-02 15:02 UTC, f-lab-jake requested changes

2023-11-02 15:02 UTC, f-lab-jake commented on BOJ/DFS/2667_단지번호붙이기.js
> +      const [newY, newX] = [y + dy[i], x + dx[i]];
`[[0,-1], [0,1]], [-1,0], [1,0]]`이란 배열을 이요해서 이부분을 다시 짜 봅시다.
지금 `4`란 값과 `dx` `dy` 는 모두 서로 커플링 되어 있습니다.

2023-11-02 15:02 UTC, f-lab-jake commented on BOJ/DFS/2667_단지번호붙이기.js
> +      dfs(i, j);
`count = 0`이 이 앞에 들어가는게 더 좋습니다. 왜그럴까요?

2023-11-02 15:02 UTC, f-lab-jake commented on BOJ/DFS/2667_단지번호붙이기.js
> +      if (newX >= 0 && newX < n && newY >= 0 && newY < n) {
이 로직도 아예 앞으로 보내버릴수 있습니다.

2023-11-03 12:31 UTC, GeonwooShin commented
- dx, dy배열을 선언해놓고 dx,dy의 각각의 인덱스 값을 참조해 더해주는 대신 상,하,좌,우에 해당하는 배열을 각각 참조하도록 수정했습니다.
- count = 0이 dfs 실행보다 앞에 있게함으로써 단지를 찾는 수행이 시작되기 전에 0으로 초기화해주는 것을 더 명확하게 드러낼 수 있을것같습니다!

```
if (newX >= 0 && newX < n && newY >= 0 && newY < n) {
        dfs(newY, newX);
}
```
위의 코드를 앞으로 보낼 수 있다고 말씀하신 부분을

```
function dfs(y, x) {
  if (
    x >= 0 &&
    x < n &&
    y >= 0 &&
    y < n &&
    apartment[y][x] === 1 &&
    isVisited[y][x] === false
  ) {
    isVisited[y][x] = true;
    count++;
    for (const move of [
      [0, -1],
      [0, 1],
      [-1, 0],
      [1, 0],
    ]) {
      const [newY, newX] = [y + move[1], x + move[0]];
      dfs(newY, newX);
    }
  }
}
```

dfs의 실행 조건 자체를 위와 같이 설정하는 것으로 이해했습니다!

2023-11-06 07:34 UTC, GeonwooShin commented
해당 pr은 머지해도될까요???!

2023-11-06 08:39 UTC, f-lab-jake commented
> 해당 pr은 머지해도될까요???!

넵 머지합시다

2023-11-06 09:35 UTC, merged