[Silver2]_1541
GeonwooShin/algorithm pull request #13
Opened 2023-11-06 11:33 UTC by GeonwooShin

문제 출처: https://www.acmicpc.net/problem/1541

`-`문자를 기준으로 나누고 나누어진 각 배열의 아이템을 `+`문자를 기준으로 나눠 덧셈을 진행하고 이후에 뺄셈을 통해 최소값으로 만들었습니다

2023-11-06 13:03 UTC, f-lab-jake requested changes

2023-11-06 13:03 UTC, f-lab-jake commented on inflearn/Greedy/잃어버린괄호.js
> +  const plusArr = i.split("+");
`plusArr`의 타입을 `number[]`로 만들어봅시다. 그게 왜 좋을까요?

2023-11-07 04:53 UTC, GeonwooShin commented
plusArr의 요소들을 모두 더해야 하는데, 요소마다 Number로 바꿔주는 작업없이 `plusArr`의 요소들을 미리 `number[]` 타입으로 바꿔놓으면 좀 더 명확할 것 같습니다!

2023-11-07 13:53 UTC, f-lab-jake commented
'좀더 명확하다'같은 표현보다 명확하게 설명할 필요가 있습니다. 예를들어 누가 '내가보기엔 안명확한데??'라고 딴지를 걸면 결국 설명을 더 해야합니다.

2023-11-07 14:22 UTC, GeonwooShin commented
plusArr의 배열을 number[] 타입으로 변경함으로써
plusArr의 요소가 숫자임을 이해할 수 있고 코드의 의도를 명확하게 전달할 수 있습니다.
이후에 plusArr 배열 요소들의 합을 진행할 때 요소마다 Number 타입으로 수정하는 일이 없게할 수 있습니다.

2023-11-08 13:36 UTC, GeonwooShin commented
plusArr 배열을 number[] 타입으로 변경함으로써
해당 부분을 숫자 배열을 준비하는 단계
밑의 부분을 준비된 숫자 배열로 연산을 처리하는 단계로 나눌 수 있기 때문에
코드가 의미하는 바를 정의할 수 있고
준비와 처리단계가 명확하게 구분되어 있기 때문에 만약 문제가 변경되는 경우 어느 부분을 수정하여 해결해야할 지 쉽게 파악할 수 있습니다.

위와 같이 정리해봤습니다!

해당 브랜치 머지 해도될까요?

2023-11-09 04:20 UTC, f-lab-jake commented
넵 머지합시다

2023-11-09 05:14 UTC, merged