[Silver1]_1946
GeonwooShin/algorithm pull request #14
Opened 2023-11-12 16:00 UTC by GeonwooShin

문제 출처: https://www.acmicpc.net/problem/1946

2023-11-13 01:31 UTC, f-lab-jake requested changes

2023-11-13 01:31 UTC, f-lab-jake commented on BOJ/Greedy/1946_신입사원.js
> +      min = interview;
이 부분이 잘 이해가 안되네요. 반대가 되어야할것 같은데요. 설명부탁드립니다.

2023-11-13 04:42 UTC, GeonwooShin commented on BOJ/Greedy/1946_신입사원.js
> +      min = interview;
가장 먼저 서류 심사 순위 기준으로 정렬을 진행했습니다.

서류 심사 순위를 기준으로 정렬된 배열은 다음과 같습니다.
`[[1,4], [2,3], [3,2], [4,1], [5,5]]`

선발될 수 있는 기준은 다른 어떤 지원자의 성적에 비해 서류 심사 순위가 높거나 면접 성적이 좋아야 합니다.
이 때 저는 서류 심사 순위 기준으로 정렬을 진행했기 때문에 서류 심사 순위가 낮은 지원자들은 앞의 지원자들보다 면접 성적이 좋아야합니다.

즉, 배열의 각각의 지원자 중 면접 심사 순위가 그 앞 지원자들의 면접 심사 순위보다 높아야(작아야)하기 때문에 위와 같이 interview 성적이 min보다 작다면 해당 interview 성적을 최소 기준으로 등록하여 다음 지원자가 만족한다면 채용하고 해당 지원자의 면접 성적을 최소로 등록하여 다음 지원자가 면접성적을 만족하는지 확인하도록 했습니다.

2023-11-13 06:36 UTC, f-lab-jake requested changes

2023-11-13 06:36 UTC, f-lab-jake commented on BOJ/Greedy/1946_신입사원.js
> +      min = interview;
아 그러니까 cnt++ 했을때 합격하는 지원자가 `v`가 아니라 `min`값의 인터뷰 점수를 들고 있던 지원자인거죠?

좀더 자연스러운 방법이 있을가요?

2023-11-13 06:58 UTC, GeonwooShin commented
cnt++ 했을 때 합격하는 지원자는 `v`가 맞습니다!

`v`지원자의 인터뷰 점수가 이전 지원자들의 인터뷰 점수 중 가장 순위가 높은(작은) `min`과 비교했을때 더 순위가 높(작)다면 `v` 지원자를 합격자로 추가하고 `v` 지원자의 인터뷰 점수를 min에 저장합니다!

2023-11-13 10:16 UTC, f-lab-jake commented
앗 그러니까 당연히 지원자는 지원자니까 `v`가 맞는데, cnt++하는 시점에서 합격하는 지원자를 얘기한거였습니다. 그것은 `min`값에 대응되는 지원자가 맞지 않나요?

2023-11-13 13:24 UTC, GeonwooShin commented
```js
for (let i = 0; i < T; i++) {
  let min = Number.MAX_SAFE_INTEGER;
  let cnt = 0;
  const N = S.shift();
  const judge = S.splice(0, N).map((v) => v.split(" ").map(Number));
  judge.sort((a, b) => a[0] - b[0]);
  judge.forEach((v) => {
    const [_, interview] = v;
    if (interview < min) {
      cnt++;
      min = interview;
    }
  });
  console.log(cnt);
}
```

제 생각엔 cnt++ 하는 시점에서 합격하는 지원자는 v가 맞는것같습니다!

1. 가장 처음 `min`의 값이 `Number.MAX_SAFE_INTEGER`이기 때문에 첫번째 지원자는 반드시 합격하는 지원자가 될것이고 min 값은 첫번째 지원자의 면접 순위가 됩니다.
2. 두번째 지원자의 면접 순위가 min(첫번째 지원자의 면접 순위) 보다 높다면(작다면) 두번째 지원자를 합격시키고 min 값은 두번째 지원자의 면접 순위가 됩니다.
...

이런식으로 이루어지는 로직입니다!

2023-11-14 01:58 UTC, f-lab-jake commented
앗 죄송합니다. 숫자가 작은게 순위가 높은 거였는데, 바보같이 그걸 계속 반대로 생각하고 있었네요. 풀이와 설명 모두 정확합니다.

2023-11-14 05:27 UTC, GeonwooShin commented
감사합니다! 해당 브랜치는 머지해도될까요??

2023-11-14 05:32 UTC, f-lab-jake approved these changes

2023-11-14 05:32 UTC, f-lab-jake commented
넵 머지합시다~

2023-11-14 06:21 UTC, merged