[Silver1]_9009
GeonwooShin/algorithm pull request #16
Opened 2023-11-14 06:21 UTC by GeonwooShin

문제 출처: https://www.acmicpc.net/problem/9009

2023-11-14 07:40 UTC, f-lab-jake requested changes

2023-11-14 07:40 UTC, f-lab-jake commented on BOJ/Greedy/9009_피보나치.js
> +const arr = [0, 1];
이제 슬슬 변수명에 신경을 써봅시다. 대부분의 경우 `arr`같은건 아무런 정보가 없는 변수입니다.
문제 풀다보니 배열이 하나 더 필요해질대마다 `arr1` `arr2`로 할 계획은 아니었을 겁니다.

우선 `fibs`정도가 좋겠습니다.

이런 변수명을 변수를 어떻게 쓸건지를 놓치면서 코딩을 하다보면 생깁니다.
그냥 아무 배열이 필요해서 `[0, 1]`이란 값을 가지는 배열을 초기화하는게 아니잖아요?
결국 그 값이 어떤의미를 갖고 어디에 쓰일지를 생각한다면 처음부터 `fibs`를 선택하게 될겁니다.

2023-11-14 07:40 UTC, f-lab-jake commented on BOJ/Greedy/9009_피보나치.js
> +for (let i = 0; i < data.length; i++) {
의미없이 인덱스를 도입하지 맙시다. `for(const i of data)`로 시작할수 있었겠죠.
`forEach`를 하거나, 아니면 `map`을 쓴다음에 출력하는 코드를 마지막으로 분리할 수 있습니다.

2023-11-14 07:40 UTC, f-lab-jake commented on BOJ/Greedy/9009_피보나치.js
> +    const newArr = arr.filter((v) => v <= num);
비효율적인 동작입니다. 이유가 뭘까요?

2023-11-14 09:37 UTC, GeonwooShin commented on BOJ/Greedy/9009_피보나치.js
> +const arr = [0, 1];
네 의미 파악이 쉽고, 가독성있는 변수명을 작성하도록 노력하겠습니다!

2023-11-14 09:38 UTC, GeonwooShin commented on BOJ/Greedy/9009_피보나치.js
> +for (let i = 0; i < data.length; i++) {
자꾸 for문을 쓰려고 하는게 습관이 된것같습니다. 이 부분도 로직에 따라 for of 또는 forEach를 사용하도록 노력하겠습니다!

2023-11-14 09:41 UTC, GeonwooShin commented on BOJ/Greedy/9009_피보나치.js
> +    const newArr = arr.filter((v) => v <= num);
반복문 내에서 filter 함수를 사용하여 새로운 배열을 계속해서 만들고 있기 때문에 비효율적이라고 생각합니다

2023-11-14 09:41 UTC, GeonwooShin commented
말씀 주신 사항들 고려하여 코드 수정해봤습니다!

2023-11-14 09:53 UTC, f-lab-jake commented on BOJ/Greedy/9009_피보나치.js
> +    const newArr = arr.filter((v) => v <= num);
맞습니다. 그런데 새로운 배열을 만드는 것은 사실 큰 문제는 아닙니다. 그보다 더 중요한 문제가 있습니다.

2023-11-14 09:54 UTC, f-lab-jake commented on BOJ/Greedy/9009_피보나치.js
> +    const newArr = arr.filter((v) => v <= num);
`fibs` 배열의 성질을 이용하면 더 효율적일수있습니다.

2023-11-14 13:52 UTC, GeonwooShin commented on BOJ/Greedy/9009_피보나치.js
> +    const newArr = arr.filter((v) => v <= num);
코드 수정사항 리뷰 부탁드립니다!

2023-11-14 14:56 UTC, f-lab-jake commented on BOJ/Greedy/9009_피보나치.js
> +  }
잘했습니다. 이렇게하면 왜 더 효율적인가요? 그리고 이렇게 고쳐도되는 근거가 무엇인가요?

2023-11-15 03:07 UTC, GeonwooShin commented on BOJ/Greedy/9009_피보나치.js
> +  }
배열을 반복해서 생성할 일 없이 간단하게 인덱스를 통해 fibo 배열의 요소에 접근하면 되기 때문에 더 효율적입니다.

fibo배열은 불변하고 num보다 작은 수들 중 가장 큰 수를 찾기 때문에 idx를 줄여가면서 접근할 수 있습니다.

2023-11-15 08:35 UTC, GeonwooShin commented
결과적으로 fibo 배열은 정렬되어있는 특징을 가지고 있고, 정렬되어 있는 배열을 filter 메서드를 통해 불필요하게 모든 요소를 순회하는 부분이 비효율적이기 때문에 수정한 코드처럼 바꿀수있는 것이라고 이해했습니다!

해당 브랜치는 머지해도될까요?

2023-11-15 08:37 UTC, merged

2023-11-15 08:37 UTC, f-lab-jake commented
앗 머지해버렸는데, `dropWhile`을 활용해서 한번 리팩토링해보세요.

2023-11-15 11:05 UTC, GeonwooShin commented
넵 알겠습니다!