[Silver3]_15649
GeonwooShin/algorithm pull request #18
Opened 2023-11-20 13:08 UTC by GeonwooShin

문제 출처: https://www.acmicpc.net/problem/15649

2023-11-21 03:12 UTC, f-lab-jake requested changes

2023-11-21 03:12 UTC, f-lab-jake commented on BOJ/BackTracking/15649_N과M.js
> +}
지금까지와 다른 방식으로 푸는 방법을 배워봅시다.
지금은 `DFS`가 `answer`를 변경하는 방식이잖아요? `DFS`가 `number[]` 타입의 정답을 리턴하는 방식으로 바꿔봅시다.

2023-11-21 03:12 UTC, f-lab-jake commented on BOJ/BackTracking/15649_N과M.js
> +}
감이 안오면 슬랙으로 질문주세요.

2023-11-21 07:48 UTC, GeonwooShin commented on BOJ/BackTracking/15649_N과M.js
> +}
```js
const input = "4 2";
const [N, M] = input.toString().trim().split(" ").map(Number);

const numbers = Array.from({ length: N }, (_, idx) => idx + 1);
const isVisited = Array.from({ length: N }, () => 0);
const selected = [];
let result = [];
function DFS(depth) {
  if (depth === M) {
    const newArr = [];
    result.push(newArr.concat(selected));
  }
  for (let i = 1; i <= numbers.length; i++) {
    if (isVisited[i]) continue;
    selected.push(i);
    isVisited[i] = 1;
    DFS(depth + 1);
    selected.pop();
    isVisited[i] = 0;
  }
  return result;
}
const answer = DFS(0);
console.log(answer);
```

위와 같이 수정하면 될까요?

2023-11-21 12:24 UTC, f-lab-jake commented on BOJ/BackTracking/15649_N과M.js
> +}
지금 DFS바깥의 변수인 results를 변경하고 있지요. 그걸 피해봅시다.

2023-11-21 12:24 UTC, f-lab-jake commented on BOJ/BackTracking/15649_N과M.js
> +}
또한 재귀호출한 DFS의 결과를 활용합시다

2023-11-21 14:22 UTC, GeonwooShin commented on BOJ/BackTracking/15649_N과M.js
> +}
어떤식으로 풀어야할지 감이 잘 안잡힙니다 ㅠㅠ 힌트를 얻을 수 있을까요?

2023-11-21 14:27 UTC, f-lab-jake commented on BOJ/BackTracking/15649_N과M.js
> +}
```
const xs = DFS(depth + 1);
```
이렇게 하고 저 xs를 활용해서 `results`를 만들어 리턴합시다

2023-11-21 16:32 UTC, GeonwooShin commented on BOJ/BackTracking/15649_N과M.js
> +}
```js
const input = "4 2";
const [N, M] = input.toString().trim().split(" ").map(Number);

const numbers = Array.from({ length: N }, (_, idx) => idx + 1);
const isVisited = Array.from({ length: N }, () => 0);
const selected = [];

function DFS(depth) {
  if (depth === M) {
    return [...selected];
  }
  const results = [];
  for (let i = 1; i <= numbers.length; i++) {
    if (isVisited[i]) continue;
    selected.push(i);
    isVisited[i] = 1;
    const xs = DFS(depth + 1);
    results.push(xs);
    selected.pop();
    isVisited[i] = 0;
  }
  return results;
}
const answer = DFS(0);
console.log(answer);
```

위와 같이 수정해봤는데 DFS 내부에서 results 배열을 반복적으로 생성하고 있어서

출력 결과가

`[
  [ [ 1, 2 ], [ 1, 3 ], [ 1, 4 ] ],
  [ [ 2, 1 ], [ 2, 3 ], [ 2, 4 ] ],
  [ [ 3, 1 ], [ 3, 2 ], [ 3, 4 ] ],
  [ [ 4, 1 ], [ 4, 2 ], [ 4, 3 ] ]
]`

이런식으로 나오는데 어느 부분을 수정할 수 있을까요?

2023-11-22 02:50 UTC, f-lab-jake commented on BOJ/BackTracking/15649_N과M.js
> +}
정답에 거의 다 왔습니다. 'results 배열을 반복적으로 생성하고 있어서' 이건 '반복적'이아니고 '중첩된'이 의도한 표현일 겁니다.

2023-11-22 12:12 UTC, merged