[Programmers]_2개이하로다른비트
GeonwooShin/algorithm pull request #3
Opened 2023-10-13 02:15 UTC by GeonwooShin

문제 출처: https://school.programmers.co.kr/learn/courses/30/lessons/77885

주어진 숫자가 짝수인 경우(이진수의 마지막 비트가 0인 수) 주어진 조건에 맞는 수는 2진수의 마지막 비트를 1로 바꾼 수이고
주어진 숫자가 홀수인 경우(이진수의 마지막 비트가 1인 수) 주어진 조건에 맞는 수는 가장 마지막 01비트를 10비트로 바꾼 수이다.

2023-10-13 09:35 UTC, f-lab-jake requested changes

2023-10-13 09:35 UTC, f-lab-jake commented on Programmers/level2/2개이하로다른비트.js
> +  return answer;
일단 `map`을 쓸수 있습니다.

문제에 숨겨진 성질을 분석해서 잘풀었습니다. 이 풀이를 찾는데 얼마나 걸렸나요?
좀더 무식한 풀이도 생각해봅시다.

2023-10-13 15:30 UTC, GeonwooShin commented on Programmers/level2/2개이하로다른비트.js
> +  return answer;
```js
function solution(numbers) {
  const answer = [];
  for (const number of numbers) {
    let bit = number.toString(2);
    let bigNumber = number + 1;
    while (true) {
      const a = bigNumber.toString(2);
      const b = bit.padStart(a.length, "0").split("");
      const c = a.split("").filter((num, idx) => num !== b[idx]);
      if (c.length <= 2) {
        answer.push(bigNumber);
        break;
      } else {
        bigNumber++;
      }
    }
  }
  return answer;
}
```

가장 먼저 작성한 코드가 위의 무식하게 풀이한 코드입니다. 시간초과가 발생해서 어떤 곳에서 시간을 줄일 수 있을지 생각하다가
도저히 떠오르지 않아 짝수와 홀수의 비트 변경이라는 힌트를 얻어 풀었습니다.

```js
function solution(numbers) {
  return numbers.map(number => {
    if (number % 2 === 0) {
      return number + 1;
    } else {
      let bit = "0" + number.toString(2);
      const idx = bit.lastIndexOf("0");
      return parseInt(`${bit.slice(0, idx)}10${bit.slice(idx + 2)}`, 2);
    }
  });
}
```

map을 사용한다면 기존 코드처럼 추가적으로 배열선언과 push메서드 사용없이 위처럼 구현할 수도 있을것같습니다!

2023-10-14 08:35 UTC, f-lab-jake commented on Programmers/level2/2개이하로다른비트.js
> +  return answer;
제가 잘못알았네요. 예전에 다른 멘티분이 무식한 풀이로 올려놔서, 그렇게해도 시간제한을 만족하는줄 알았습니다.
입력값 크기를 보니 지금처럼 성질을 관찰해서 나온 풀이만 유효하겠네요. 나머지 디테일은 멘토링때 얘기합시다.

2023-10-14 10:51 UTC, GeonwooShin commented on Programmers/level2/2개이하로다른비트.js
> +  return answer;
네 알겠습니다!

2023-10-14 10:51 UTC, merged