Feat/programmers/level2/택배상자
GeonwooShin/algorithm pull request #4
Opened 2023-10-15 09:29 UTC by GeonwooShin

문제 출처: https://school.programmers.co.kr/learn/courses/30/lessons/131704

문제 접근 방법

- 순서에 맞는 상자가 컨테이너 벨트 쪽에 있다면 그 번호가 나올때까지 보조 컨테이너 벨트에 넣는다.
- 순서에 맞는 상자가 컨테이너 벨트 쪽에 없다면 보조 컨테이너의 가장 바깥쪽 상자와 비교한다.

2023-10-15 12:00 UTC, f-lab-jake requested changes

2023-10-15 12:00 UTC, f-lab-jake commented on Programmers/level2/택배상자.js
> +  for (let i = 0; i < order.length; i++) {
인덱스가 필요없을땐 for of를 씁시다. `answer`대신에 `i`를 답으로 쓰면 정당화되는 방식입니다

2023-10-15 12:00 UTC, f-lab-jake commented on Programmers/level2/택배상자.js
> +        flag = false;
그냥 break를 하는게 어떨까요?

2023-10-15 12:00 UTC, f-lab-jake commented on Programmers/level2/택배상자.js
> +      if (order[i] === subContainer[subContainer.length - 1]) {
`subContainer.at(-1)`로 대신쓸수 있습니다.

2023-10-15 12:30 UTC, GeonwooShin commented
리뷰 주신 내용 바탕으로 코드 수정했습니다!

2023-10-15 16:22 UTC, f-lab-jake approved these changes

2023-10-15 16:22 UTC, f-lab-jake commented on Programmers/level2/택배상자.js
> +      if (box === subContainer.at(-1)) {
추가로 고려해볼만한 개선이 있는데요.
`subContainer.at(-1)`랑 `subContainer.pop()`가 같은 의미의 서로 다른 표현이란걸 알수있습니다. 그래서 `pop`해준다음에 그 값을 비교하고 다시 넣어주는 방법도 있습니다. 성능에 해가 되서 이경우에 굳이 그렇게 하는건 좀 뻘짓인데, 비슷한 방식으로 코드를 개선할수있는 다른 경우들이 있습니다.

2023-10-16 08:14 UTC, GeonwooShin commented on Programmers/level2/택배상자.js
> +      if (box === subContainer.at(-1)) {
`subContainer.at(-1)`과 `subContainer.pop()` 모두 배열의 마지막 요소와 관련있다 라는 포인트 확인했습니다!

멘토님 말씀대로 이 문제의 경우에서는 pop을 통해 마지막 요소를 1. 빼고 2. 비교하고 3. 다시 넣어준다 라는 측면에서는 성능에 해가되는것 같습니다. 

추후에 관련 로직을 사용할 수 있는 문제가 있으면 사용해보도록 하겠습니다!

2023-10-16 08:14 UTC, merged

2023-10-16 13:05 UTC, f-lab-jake commented on Programmers/level2/택배상자.js
> +      if (box === subContainer.at(-1)) {
아 다시보니 `pop`이면 성능에 거의 영향도 없겠네요. `unshift`라고 착각했습니다ㅋㅋ
언어에 따라 `pop`하고 다시 넣는게 성능에 영향이 없기도합니다. 그럴땐 의미를 더 잘살린 코드를 짤수있게됩니다.