Feat/inflearn/송아지찾기
GeonwooShin/algorithm pull request #8
Opened 2023-10-23 12:46 UTC by GeonwooShin

문제

> 현수는 송아지를 잃어버렸다. 다행히 송아지에는 위치추적기가 달려 있다. 현수의 위치와 송아 지의 위치가 수직선상의 좌표 점으로 주어지면 현수는 현재 위치에서 송아지의 위치까지 다음 과 같은 방법으로 이동한다. 송아지는 움직이지 않고 제자리에 있다.
현수는 스카이 콩콩을 타고 가는데 한 번의 점프로 앞으로 1, 뒤로 1, 앞으로 5를 이동할 수 있다. 최소 몇 번의 점프로 현수가 송아지의 위치까지 갈 수 있는지 구하는 프로그램을 작성 하세요.

> 첫 번째 줄에 현수의 위치 S와 송아지의 위치 E가 주어진다. 직선의 좌표 점은 1부터 10,000 까지이다.

2023-10-24 02:52 UTC, f-lab-jake requested changes

2023-10-24 02:52 UTC, f-lab-jake commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
왜 bfs로 해야할까요?

그리고 `ch`가 지난번의 `isVirus`와 같은 용도잖아요? 그때 했던것과 같은 방식의 개선을 해봅시다.

2023-10-25 13:23 UTC, GeonwooShin commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
모든 조합을 따져서 특정 위치로 갈수있는 최소 길이를 구해야하기 때문에 BFS를 사용해야한다고 생각했습니다.
```
function solution(S, E) {
  const distance = Array.from(Array(E + 1), () => 0);
  const ch = Array.from(Array(E + 1), () => 0);
  const queue = [S];
  while (queue.length) {
    const location = queue.shift();
    ch[location] = 1;
    for (let move of [location - 1, location + 1, location + 5]) {
      if (move === E) return distance[location] + 1;
      if (move > 0 && move <= 10000 && ch[move] === 0) {
        ch[move] = 1;
        queue.push(move);
        distance[move] = distance[location] + 1;
      }
    }
  }
}
```
저번에 커플링을 줄이기 위해 isVirus를 dfs 함수 내부에서 처리하라고 하셨었는데
위처럼 while 문 내에서 큐에서 빼온 위치에 따라 처리하도록 수정하면 괜찮을것같아요!

2023-10-25 13:32 UTC, f-lab-jake commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
`ch[move] = 1;` 요건 빠져야겠죠? 그리고 `ch[move] === 0` 이 조건도 여기있으면 안됩니다.

또, 지금 `if (move === E) return distance[location] + 1;` 이렇게 도착하면 바로 리턴하고 있는데, 이렇게 풀어도 되는 이유가 뭘까요?

2023-10-25 16:08 UTC, GeonwooShin commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
`ch[move] === 0` 조건은 해당 위치에 방문한 적이 없는 경우에 `queue`에 해당 위치를 넣는 연산을 하기위한 조건인데, 방문한 적이 있는 위치라면 반복적인 연산을 피하기 위해서 넣은 조건입니다. 필요한 조건이지만 넣는 위치가 잘못됐다고 이해하면될까요??!

`if (move === E) return distance[location] + 1;` 을 통해 리턴하는 경우는 각각의 위치가 몇번만에 위치했는지를 distance 배열에 저장해주고있기 때문에 바로 리턴해줘도 된다고 생각했습니다!

2023-10-26 06:35 UTC, f-lab-jake commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
`ch[location] = 1;`에 방문여부를 체크하는 로직을 유일화했으니, 코드의 다른부분이 거기에 맞춰 바뀌어야합니다.

2023-10-26 06:36 UTC, f-lab-jake commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
'바로' 리턴해줘도 되는 이유가 뭘까요? 더 찾을 필요가 없나요?

2023-10-26 12:45 UTC, GeonwooShin commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
그래프에서 각 위치의 -1, +1, *5에 해당하는 위치들을 확인하여 원하는 도착지점과 동일하다면 너비 우선탐색이기 때문에 최소한의 이동일 수 밖에없으니 바로 리턴해줄 수 있을 것 같습니다!

2023-10-26 12:51 UTC, GeonwooShin commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
`ch[location] = 1;` 유일화를 통해 방문 지점을 체크해주는 방식은 이해했는데, 어느 부분이 더 바뀌어야하는지 캐치하지 못했습니다ㅠㅠ

2023-10-26 13:13 UTC, f-lab-jake commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
```typescript
function solution(S, E) {
  const distance = Array.from(Array(E + 1), () => 0);
  const ch = Array.from(Array(E + 1), () => 0);
  const queue = [S];
  while (queue.length) {
    const location = queue.shift();
    if (ch[location]) continue;
    ch[location] = 1;
    for (let move of [location - 1, location + 1, location + 5]) {
      if (move === E) return distance[location] + 1;
      if (move > 0 && move <= 10000 && ch[move] === 0) {
        queue.push(move);
        distance[move] = distance[location] + 1;
      }
    }
  }
}
```

요런식이 되어야겠죠? 사실 `queue.push`와 `distance[move] = distance[location] + 1`와도 커플링이 되어있습니다.

2023-10-26 14:39 UTC, GeonwooShin commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
```
function solution(S, E) {
  const distance = Array.from(Array(E + 1), () => 0);
  const ch = Array.from(Array(E + 1), () => 0);
  const queue = [S];
  while (queue.length) {
    const location = queue.shift();
    if (ch[location]) continue;
    ch[location] = 1;
    for (let move of [location - 1, location + 1, location + 5]) {
      if (move === E) return distance[location] + 1;
      if (move > 0 && move <= 10000 && ch[move] === 0) {
        queue.push(move);
        distance[move] = distance[location] + 1;
      }
    }
  }
}
```
위처럼 `if(ch[location]) continue` 조건은 ` if (move > 0 && move <= 10000 && ch[move] === 0)` 이 조건에서 처리될 수 있는 부분아닌가요!?!

```
function solution(S, E) {
  const distance = Array.from(Array(E + 1), () => 0);
  const ch = Array.from(Array(E + 1), () => 0);
  const queue = [S];
  while (queue.length) {
    const location = queue.shift();
    if (ch[location]) continue;
    ch[location] = 1;
    for (let move of [location - 1, location + 1, location + 5]) {
      if (move === E) return distance[location] + 1;
      if (move > 0 && move <= 10000 ) {
        queue.push(move);
        distance[move] = distance[location] + 1;
      }
    }
  }
}
```
이 코드처럼 `ch[move] === 0` 조건을 삭제하면 말씀해주신 내용이 이해가 될것같습니다!!

2023-10-27 00:44 UTC, f-lab-jake commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
아 네네 맞습니다. 제가 그걸 지우는걸 깜빡했네요. 이해를 제대로한게 맞습니다.

2023-10-27 06:03 UTC, GeonwooShin commented on inflearn/DFS&BFS/송아지찾기.js
> +  }
이해했습니다 감사합니다!

2023-10-27 06:03 UTC, merged